//! Producer domain for the Raft state machine.
//!
//! Handles producer ID allocation, idempotency state, and transactions.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;

use super::serde_helpers::serialize_sorted_map;

/// How many recent (request_token, producer_id) allocations to remember
/// so a `client_write` retry that lands two `AllocateProducerId` entries
/// in the log returns the same producer_id both times instead of minting
/// a duplicate. 4096 covers a generous burst of in-flight allocations
/// while bounding FSM-state growth and snapshot cost.
const ALLOC_DEDUP_WINDOW: usize = 4096;

/// Producer state for idempotency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProducerIdempotencyState {
    pub producer_id: i64,
    pub producer_epoch: i16,
    pub last_sequence: i32,
    /// Timestamp of last update (used for eviction).
    pub last_updated_ms: u64,
}

/// Transaction state.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum TransactionState {
    Empty,
    Ongoing,
    PrepareCommit,
    PrepareAbort,
    CompleteCommit,
    CompleteAbort,
    Dead,
}

/// Transactional producer state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionalProducerInfo {
    pub transactional_id: String,
    pub producer_id: i64,
    pub producer_epoch: i16,
    pub state: TransactionState,
    pub timeout_ms: i32,
    pub last_update_ms: u64,
}

/// Commands for the producer domain.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProducerCommand {
    /// Allocate a new producer ID.
    ///
    /// `request_token` is a per-call UUID generated by the proposer.
    /// `client_write` is not idempotent — if the leader commits this
    /// entry then crashes before responding, the proposer retries and
    /// a duplicate entry would be committed, minting two producer IDs
    /// for one client request. The FSM caches the most recent allocations
    /// keyed on this token and returns the cached id on replay.
    /// `None` preserves the legacy non-idempotent behaviour for older
    /// callers / replay of pre-upgrade entries.
    AllocateProducerId { request_token: Option<u128> },

    /// Initialize a producer (possibly transactional).
    ///
    /// `request_token` collapses two committed entries that came from a
    /// single `client_write` retry into one allocation. The handler mints
    /// the token at the Kafka request boundary (so the same SDK request
    /// retried at the openraft layer carries the same token through to
    /// the FSM). `None` preserves the legacy non-deduped path for older
    /// callers / replay of pre-upgrade entries.
    InitProducerId {
        transactional_id: Option<String>,
        producer_id: i64,
        epoch: i16,
        timeout_ms: i32,
        timestamp_ms: u64,
        #[serde(default)]
        request_token: Option<u128>,
    },

    /// Store producer state for idempotency.
    StoreProducerState {
        topic: String,
        partition: i32,
        producer_id: i64,
        last_sequence: i32,
        producer_epoch: i16,
        timestamp_ms: u64,
    },

    /// Expire producer states that haven't been updated within the TTL.
    ExpireProducerStates { current_time_ms: u64, ttl_ms: u64 },
}

/// Responses from producer domain operations.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProducerResponse {
    /// Producer ID was allocated.
    ProducerIdAllocated { producer_id: i64, epoch: i16 },

    /// Producer state was stored.
    ProducerStateStored,

    /// Producer states were expired.
    ProducerStatesExpired { count: usize },

    /// The client-supplied `(producer_id, epoch)` did not match the stored
    /// pair for the given `transactional_id`. KIP-360 mandates this typed
    /// signal so the client retires the producer rather than retrying with
    /// the same identity. Emitted when a previously-fenced producer tries
    /// to resume after the broker has bumped/replaced its epoch.
    ProducerFenced {
        stored_producer_id: i64,
        stored_epoch: i16,
    },

    /// Generic success.
    Ok,
}

/// State for the producer domain.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ProducerDomainState {
    /// Next producer ID to allocate.
    pub next_producer_id: i64,

    /// Transactional producers.
    #[serde(serialize_with = "serialize_sorted_map")]
    pub transactional_producers: HashMap<String, TransactionalProducerInfo>,

    /// Producer states for idempotency: (topic, partition, producer_id) -> ProducerIdempotencyState.
    #[serde(serialize_with = "serialize_sorted_map")]
    pub producer_states: HashMap<(Arc<str>, i32, i64), ProducerIdempotencyState>,

    /// Recent (request_token, producer_id) allocations for AllocateProducerId
    /// dedup. Bounded ring (`ALLOC_DEDUP_WINDOW`) so FSM state and snapshot
    /// cost stay flat. Older entries fall off the back; a retry that arrives
    /// after eviction degrades to legacy non-idempotent behaviour, which is
    /// acceptable for a window that exceeds normal in-flight allocation
    /// counts by orders of magnitude.
    #[serde(default)]
    pub recent_allocations: VecDeque<(u128, i64)>,
}

impl ProducerDomainState {
    /// Create a new empty producer state.
    pub fn new() -> Self {
        Self::default()
    }

    /// Apply a producer command and return the response.
    pub fn apply(&mut self, cmd: ProducerCommand) -> ProducerResponse {
        match cmd {
            ProducerCommand::AllocateProducerId { request_token } => {
                if let Some(token) = request_token
                    && let Some((_, cached_id)) =
                        self.recent_allocations.iter().find(|(t, _)| *t == token)
                {
                    return ProducerResponse::ProducerIdAllocated {
                        producer_id: *cached_id,
                        epoch: 0,
                    };
                }
                let producer_id = self.next_producer_id;
                self.next_producer_id += 1;
                if let Some(token) = request_token {
                    if self.recent_allocations.len() >= ALLOC_DEDUP_WINDOW {
                        self.recent_allocations.pop_front();
                    }
                    self.recent_allocations.push_back((token, producer_id));
                }
                ProducerResponse::ProducerIdAllocated {
                    producer_id,
                    epoch: 0,
                }
            }

            ProducerCommand::InitProducerId {
                transactional_id,
                producer_id: client_pid,
                epoch: client_epoch,
                timeout_ms,
                timestamp_ms,
                request_token,
            } => {
                // First, look for a previously-allocated id under the same
                // request_token. A `client_write` retry that arrives after
                // the leader has already committed the original entry must
                // observe the SAME producer_id/epoch — minting a fresh one
                // here would split idempotency: the client thinks one
                // InitProducerId call returned PID X, but the broker has
                // also burned PID X+1 with a different epoch, and any
                // produces under PID X+1 from the leader-side first-attempt
                // future are now orphaned.
                if let Some(token) = request_token
                    && let Some((_, cached_id)) =
                        self.recent_allocations.iter().find(|(t, _)| *t == token)
                {
                    // The cached_id may belong to either branch; for the
                    // transactional path we still need to surface the
                    // current epoch on the stored entry. For the
                    // non-transactional branch, epoch is always 0.
                    if let Some(txn_id) = &transactional_id
                        && let Some(entry) = self.transactional_producers.get(txn_id)
                        && entry.producer_id == *cached_id
                    {
                        return ProducerResponse::ProducerIdAllocated {
                            producer_id: entry.producer_id,
                            epoch: entry.producer_epoch,
                        };
                    }
                    return ProducerResponse::ProducerIdAllocated {
                        producer_id: *cached_id,
                        epoch: 0,
                    };
                }

                let response = if let Some(txn_id) = transactional_id {
                    // Transactional producer
                    if let Some(entry) = self.transactional_producers.get_mut(&txn_id) {
                        let claiming_recovery = client_pid >= 0 || client_epoch >= 0;
                        if claiming_recovery
                            && (client_pid != entry.producer_id
                                || client_epoch != entry.producer_epoch)
                        {
                            tracing::warn!(
                                transactional_id = %txn_id,
                                client_producer_id = client_pid,
                                client_epoch = client_epoch,
                                stored_producer_id = entry.producer_id,
                                stored_epoch = entry.producer_epoch,
                                "InitProducerId fenced: client (pid, epoch) does not match stored"
                            );
                            return ProducerResponse::ProducerFenced {
                                stored_producer_id: entry.producer_id,
                                stored_epoch: entry.producer_epoch,
                            };
                        }
                        if entry.producer_epoch == i16::MAX {
                            let new_pid = self.next_producer_id;
                            self.next_producer_id += 1;
                            tracing::warn!(
                                transactional_id = %txn_id,
                                old_producer_id = entry.producer_id,
                                new_producer_id = new_pid,
                                "Producer epoch saturated at i16::MAX; allocating fresh producer_id and resetting epoch to 0"
                            );
                            entry.producer_id = new_pid;
                            entry.producer_epoch = 0;
                        } else {
                            entry.producer_epoch += 1;
                        }
                        entry.last_update_ms = timestamp_ms;
                        ProducerResponse::ProducerIdAllocated {
                            producer_id: entry.producer_id,
                            epoch: entry.producer_epoch,
                        }
                    } else {
                        if client_pid >= 0 || client_epoch >= 0 {
                            return ProducerResponse::ProducerFenced {
                                stored_producer_id: -1,
                                stored_epoch: -1,
                            };
                        }
                        let pid = self.next_producer_id;
                        self.next_producer_id += 1;
                        self.transactional_producers.insert(
                            txn_id.clone(),
                            TransactionalProducerInfo {
                                transactional_id: txn_id,
                                producer_id: pid,
                                producer_epoch: 0,
                                state: TransactionState::Empty,
                                timeout_ms,
                                last_update_ms: timestamp_ms,
                            },
                        );
                        ProducerResponse::ProducerIdAllocated {
                            producer_id: pid,
                            epoch: 0,
                        }
                    }
                } else {
                    let producer_id = self.next_producer_id;
                    self.next_producer_id += 1;
                    ProducerResponse::ProducerIdAllocated {
                        producer_id,
                        epoch: 0,
                    }
                };

                // Cache the freshly-allocated id under the token so a
                // retry that lands a duplicate entry returns the same
                // value. Only cache the success path; a fenced response
                // is not retry-stable (the client is supposed to abort).
                if let (Some(token), ProducerResponse::ProducerIdAllocated { producer_id, .. }) =
                    (request_token, &response)
                {
                    if self.recent_allocations.len() >= ALLOC_DEDUP_WINDOW {
                        self.recent_allocations.pop_front();
                    }
                    self.recent_allocations.push_back((token, *producer_id));
                }

                response
            }

            ProducerCommand::StoreProducerState {
                topic,
                partition,
                producer_id,
                last_sequence,
                producer_epoch,
                timestamp_ms,
            } => {
                let topic: Arc<str> = Arc::from(topic);
                let key = (topic, partition, producer_id);
                self.producer_states.insert(
                    key,
                    ProducerIdempotencyState {
                        producer_id,
                        producer_epoch,
                        last_sequence,
                        last_updated_ms: timestamp_ms,
                    },
                );
                ProducerResponse::ProducerStateStored
            }

            ProducerCommand::ExpireProducerStates {
                current_time_ms,
                ttl_ms,
            } => {
                // Collect keys to remove
                let keys_to_remove: Vec<_> = self
                    .producer_states
                    .iter()
                    .filter(|(_, state)| {
                        current_time_ms.saturating_sub(state.last_updated_ms) > ttl_ms
                    })
                    .map(|(key, _)| key.clone())
                    .collect();

                let count = keys_to_remove.len();
                for key in keys_to_remove {
                    self.producer_states.remove(&key);
                }

                ProducerResponse::ProducerStatesExpired { count }
            }
        }
    }

    /// Get producer idempotency state.
    pub fn get_producer_state(
        &self,
        topic: &str,
        partition: i32,
        producer_id: i64,
    ) -> Option<&ProducerIdempotencyState> {
        let key = (Arc::from(topic), partition, producer_id);
        self.producer_states.get(&key)
    }

    /// Get transactional producer info.
    pub fn get_transactional_producer(
        &self,
        transactional_id: &str,
    ) -> Option<&TransactionalProducerInfo> {
        self.transactional_producers.get(transactional_id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_allocate_producer_id() {
        let mut state = ProducerDomainState::new();

        let response = state.apply(ProducerCommand::AllocateProducerId {
            request_token: None,
        });
        match response {
            ProducerResponse::ProducerIdAllocated { producer_id, epoch } => {
                assert_eq!(producer_id, 0);
                assert_eq!(epoch, 0);
            }
            _ => panic!("Expected ProducerIdAllocated"),
        }

        let response = state.apply(ProducerCommand::AllocateProducerId {
            request_token: None,
        });
        match response {
            ProducerResponse::ProducerIdAllocated { producer_id, .. } => {
                assert_eq!(producer_id, 1);
            }
            _ => panic!("Expected ProducerIdAllocated"),
        }
    }

    #[test]
    fn test_init_transactional_producer() {
        let mut state = ProducerDomainState::new();

        let response = state.apply(ProducerCommand::InitProducerId {
            transactional_id: Some("txn-1".to_string()),
            producer_id: -1,
            epoch: -1,
            timeout_ms: 60000,
            timestamp_ms: 1000,
            request_token: None,
        });

        match response {
            ProducerResponse::ProducerIdAllocated { producer_id, epoch } => {
                assert_eq!(producer_id, 0);
                assert_eq!(epoch, 0);
            }
            _ => panic!("Expected ProducerIdAllocated"),
        }

        // Re-init with the matching (pid, epoch) should bump epoch.
        let response = state.apply(ProducerCommand::InitProducerId {
            transactional_id: Some("txn-1".to_string()),
            producer_id: 0,
            epoch: 0,
            timeout_ms: 60000,
            timestamp_ms: 2000,
            request_token: None,
        });

        match response {
            ProducerResponse::ProducerIdAllocated { producer_id, epoch } => {
                assert_eq!(producer_id, 0);
                assert_eq!(epoch, 1);
            }
            _ => panic!("Expected ProducerIdAllocated"),
        }
    }

    #[test]
    fn test_store_producer_state() {
        let mut state = ProducerDomainState::new();

        let response = state.apply(ProducerCommand::StoreProducerState {
            topic: "test".to_string(),
            partition: 0,
            producer_id: 123,
            last_sequence: 5,
            producer_epoch: 0,
            timestamp_ms: 1000,
        });

        assert!(matches!(response, ProducerResponse::ProducerStateStored));

        let producer_state = state.get_producer_state("test", 0, 123).unwrap();
        assert_eq!(producer_state.last_sequence, 5);
    }

    #[test]
    fn test_expire_producer_states() {
        let mut state = ProducerDomainState::new();

        state.apply(ProducerCommand::StoreProducerState {
            topic: "test".to_string(),
            partition: 0,
            producer_id: 1,
            last_sequence: 1,
            producer_epoch: 0,
            timestamp_ms: 1000,
        });

        state.apply(ProducerCommand::StoreProducerState {
            topic: "test".to_string(),
            partition: 1,
            producer_id: 2,
            last_sequence: 1,
            producer_epoch: 0,
            timestamp_ms: 2000,
        });

        // Expire with TTL of 500ms, current time 1600ms
        // First state (1000ms) should expire, second (2000ms) should not
        let response = state.apply(ProducerCommand::ExpireProducerStates {
            current_time_ms: 1600,
            ttl_ms: 500,
        });

        match response {
            ProducerResponse::ProducerStatesExpired { count } => {
                assert_eq!(count, 1);
            }
            _ => panic!("Expected ProducerStatesExpired"),
        }

        assert!(state.get_producer_state("test", 0, 1).is_none());
        assert!(state.get_producer_state("test", 1, 2).is_some());
    }
}
