//! Durability-contract property test.
//!
//! Asserts the contract documented in `README.md`:
//!
//!   If `append_batch_durable` returns `Ok(base_offset)`, the batch is
//!   present after a "crash" (drop the store without flushing) and
//!   re-open against the same backing object store.
//!
//! The schedule is generated by `fastrand` so the test exercises a
//! different interleaving on every run; failures reproduce by re-running
//! with `KAFKAESQUE_DURABILITY_SEED=<seed>`.
//!
//! `acks=0` writes (`append_batch`) are intentionally NOT covered by the
//! invariant — the broker has explicitly opted out of durability for
//! those, and SlateDB's periodic flush window can lose them on a hard
//! kill. The test still issues a few of them to verify they don't
//! corrupt the durable batches around them.

use bytes::Bytes;
use kafkaesque::cluster::PartitionStore;
use object_store::ObjectStore;
use object_store::memory::InMemory;
use std::collections::BTreeMap;
use std::sync::Arc;

const TOPIC: &str = "durability-contract";
const PARTITION: i32 = 0;
const BASE_PATH: &str = "durability-contract-test";

/// CRC-32C (Castagnoli) — same constant as the rest of the test code.
fn crc32c(data: &[u8]) -> u32 {
    const TABLE: [u32; 256] = {
        let mut t = [0u32; 256];
        let mut i = 0;
        while i < 256 {
            let mut crc = i as u32;
            let mut j = 0;
            while j < 8 {
                if crc & 1 != 0 {
                    crc = (crc >> 1) ^ 0x82F63B78;
                } else {
                    crc >>= 1;
                }
                j += 1;
            }
            t[i] = crc;
            i += 1;
        }
        t
    };

    let mut crc = !0u32;
    for &b in data {
        let idx = ((crc ^ b as u32) & 0xFF) as usize;
        crc = (crc >> 8) ^ TABLE[idx];
    }
    !crc
}

/// Build a non-idempotent record batch (producer_id = -1) of size
/// `record_count`. The batch shape mirrors the helpers in
/// `partition_store_tests.rs`.
fn build_batch(record_count: i32) -> Bytes {
    let mut batch = vec![0u8; 100];

    // base_offset (will be patched by PartitionStore)
    batch[0..8].copy_from_slice(&0i64.to_be_bytes());
    // batch_length
    batch[8..12].copy_from_slice(&(100i32 - 12).to_be_bytes());
    // partition_leader_epoch
    batch[12..16].copy_from_slice(&0i32.to_be_bytes());
    // magic
    batch[16] = 2;
    // attributes
    batch[21..23].copy_from_slice(&0i16.to_be_bytes());
    // last_offset_delta
    batch[23..27].copy_from_slice(&(record_count - 1).to_be_bytes());
    // first_timestamp / max_timestamp
    batch[27..35].copy_from_slice(&0i64.to_be_bytes());
    batch[35..43].copy_from_slice(&0i64.to_be_bytes());
    // producer_id = -1 (non-idempotent)
    batch[43..51].copy_from_slice(&(-1i64).to_be_bytes());
    // producer_epoch = 0
    batch[51..53].copy_from_slice(&0i16.to_be_bytes());
    // first_sequence = 0
    batch[53..57].copy_from_slice(&0i32.to_be_bytes());
    // record_count
    batch[57..61].copy_from_slice(&record_count.to_be_bytes());

    let crc = crc32c(&batch[21..]);
    batch[17..21].copy_from_slice(&crc.to_be_bytes());

    Bytes::from(batch)
}

/// One scheduled action.
enum Action {
    /// `acks=0` produce — record the offset but do NOT add it to the
    /// durable-acks set. Loss across crash is acceptable.
    FastAppend { record_count: i32 },
    /// `acks>=1` produce — record the offset and assert it survives.
    DurableAppend { record_count: i32 },
    /// Drop the store without calling `flush`/`close` and re-open.
    Crash,
    /// Call `flush()` and continue (no reopen).
    Flush,
}

fn gen_action(rng: &mut fastrand::Rng) -> Action {
    // Bias the schedule toward writes; one in ~6 actions is a crash so
    // every iteration sees several reopens.
    match rng.u32(0..100) {
        0..=59 => Action::DurableAppend {
            record_count: rng.i32(1..=4),
        },
        60..=79 => Action::FastAppend {
            record_count: rng.i32(1..=4),
        },
        80..=89 => Action::Flush,
        _ => Action::Crash,
    }
}

async fn open(object_store: Arc<dyn ObjectStore>) -> PartitionStore {
    PartitionStore::open(object_store, BASE_PATH, TOPIC, PARTITION)
        .await
        .expect("open partition store")
}

/// Run one randomized schedule of `n_actions` against a single backing
/// `InMemory` object store. Returns Ok(()) when every durable ack
/// survived its subsequent crash; panics with the seed and the offset
/// that went missing on failure.
async fn run_schedule(seed: u64, n_actions: usize) {
    let object_store: Arc<dyn ObjectStore> = Arc::new(InMemory::new());
    let mut rng = fastrand::Rng::with_seed(seed);

    // base_offset -> record_count for every batch we have a durable ack
    // for. Must remain readable across every subsequent reopen.
    let mut durable_acks: BTreeMap<i64, i32> = BTreeMap::new();
    let mut store = open(object_store.clone()).await;

    for step in 0..n_actions {
        match gen_action(&mut rng) {
            Action::DurableAppend { record_count } => {
                let batch = build_batch(record_count);
                match store.append_batch_durable(&batch).await {
                    Ok(base_offset) => {
                        let prev = durable_acks.insert(base_offset, record_count);
                        assert!(
                            prev.is_none(),
                            "seed={seed} step={step}: broker re-issued base_offset {base_offset}"
                        );
                    }
                    Err(e) => panic!("seed={seed} step={step}: durable append failed: {e}"),
                }
            }
            Action::FastAppend { record_count } => {
                let batch = build_batch(record_count);
                // acks=0: success or transient failure both acceptable;
                // we just want to confirm the call doesn't panic and
                // doesn't poison the store for the subsequent durable
                // writes.
                let _ = store.append_batch(&batch).await;
            }
            Action::Flush => {
                store.flush().await.expect("flush");
            }
            Action::Crash => {
                // Drop without flush/close — simulates SIGKILL / OOM
                // between WAL flushes. Any durable ack we issued before
                // this point must still be present after reopen.
                drop(store);
                store = open(object_store.clone()).await;

                // Recovery is only obligated to expose offsets up to
                // the durable HWM. Confirm every durable ack base_offset
                // is below the HWM, and that fetch_from returns Some.
                let hwm = store.high_watermark();
                if let Some((max_acked_base, max_acked_count)) = durable_acks.iter().next_back() {
                    let expected_min_hwm = *max_acked_base + *max_acked_count as i64;
                    assert!(
                        hwm >= expected_min_hwm,
                        "seed={seed} step={step}: HWM regressed after crash. \
                         hwm={hwm}, expected >= {expected_min_hwm} \
                         (last durable ack: base={max_acked_base}, count={max_acked_count})",
                    );
                }
                for (base_offset, _record_count) in durable_acks.iter() {
                    let (_hwm, records) = store.fetch_from(*base_offset).await.expect("fetch_from");
                    assert!(
                        records.is_some(),
                        "seed={seed} step={step}: durable ack at base_offset {base_offset} \
                         missing after crash",
                    );
                }
            }
        }
    }

    // Final crash + verify, so the last durable ack also gets a
    // post-crash check.
    drop(store);
    let store = open(object_store.clone()).await;
    for (base_offset, _) in durable_acks.iter() {
        let (_hwm, records) = store.fetch_from(*base_offset).await.expect("fetch_from");
        assert!(
            records.is_some(),
            "seed={seed} final: durable ack at base_offset {base_offset} missing after crash",
        );
    }
}

/// Resolve the seed list. Defaults to a fixed set so CI is
/// deterministic; override with `KAFKAESQUE_DURABILITY_SEED=<u64>` to
/// reproduce a single failure or pin a long run.
fn seeds() -> Vec<u64> {
    if let Ok(seed_env) = std::env::var("KAFKAESQUE_DURABILITY_SEED") {
        return seed_env
            .split(',')
            .filter_map(|s| s.trim().parse::<u64>().ok())
            .collect();
    }
    // Eight schedules cover ~enough action-interleaving variety for
    // a per-PR signal without slowing the suite. Increase locally
    // when chasing a flake.
    vec![
        0x0123_4567_89ab_cdef,
        0xdead_beef_cafe_babe,
        0xfeed_face_8bad_f00d,
        0x1234_5678_90ab_cdef,
        0x0fed_cba9_8765_4321,
        0xa5a5_a5a5_5a5a_5a5a,
        0x0001_0203_0405_0607,
        0x7fff_ffff_ffff_ffff,
    ]
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn durable_acks_survive_random_crash_schedule() {
    for seed in seeds() {
        run_schedule(seed, 40).await;
    }
}
